version: '3.9'

services:
  fal2claude:
    build: .
    container_name: fal2claude
    ports:
      - "8080:8080"
    environment:
      # API Key (可选，推荐从请求头 x-api-key 传入)
      - FAL_KEY=${FAL_KEY:-}

      # 服务端口
      - PORT=8080

      # 模型映射配置 (JSON 格式)
      # 用途: 将请求的 Claude 模型名映射到实际调用的 Fal 模型
      # 格式: {"请求的模型名": "实际调用的fal模型名"}
      # 示例: 请求 claude-3-5-sonnet-20241022 → 实际调用 google/gemini-2.5-flash
      #       请求 claude-3-haiku-20240307 → 实际调用 google/gemini-2.5-flash-lite
      # 默认值提供了常用的 Claude 模型映射
      - MODEL_MAPPING=${MODEL_MAPPING:-{"claude-sonnet-4-5-20250929":"anthropic/claude-3.7-sonnet","claude-opus-4-1-20250805":"anthropic/claude-3.7-sonnet","claude-3-5-haiku-20241022":"google/gemini-2.5-flash"}}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s